server:
  port: 8888

  servlet:
    context-path: /uaa

spring:
  application:
    name: uaa-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///oauth?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: info

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
