server:
  port: 8080

spring:
  application:
    name: discovery
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka/
    fetch-registry: false
    register-with-eureka: false
  instance:
    lease-renewal-interval-in-seconds: 30 # 心跳
    lease-expiration-duration-in-seconds: 10 # 过期时间
    prefer-ip-address: true
  server:
    enable-self-preservation: false # 关闭自我保护
    eviction-interval-timer-in-ms: 10
