server:
  port: 8888
  servlet:
    context-path: /

spring:
  application:
    name: security-oauth2
  mvc:
    view:
      prefix: /
      suffix: .html

  datasource:
    url: jdbc:mysql:///oauth?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

